name: 1MB-MapHide
version: '${version}'
main: com.technicjelle.bluemapplayercontrol.BlueMapPlayerControl
folia-supported: true
api-version: '1.21'
depend:
  - BlueMap
softdepend:
  - PlaceholderAPI
authors:
  - TechnicJelle
  - mrfloris
description: Adds player hiding functionality to BlueMap.
website: https://docs.1moreblock.com/custom-server-plugins/maphide/

commands:
  bmpc:
    usage: /<command> [help|info|toggle|show|hide|status|config|debug|reload]
    description: BlueMap marker visibility command.

permissions:
  maphide.player:
    default: true
    children:
      maphide.player.help: true
      maphide.player.info: true
      maphide.player.toggle: true
      maphide.player.show: true
      maphide.player.hide: true
  maphide.player.help:
    default: true
  maphide.player.info:
    default: true
  maphide.player.toggle:
    default: true
  maphide.player.show:
    default: true
  maphide.player.hide:
    default: true
  maphide.forcehide:
    default: false
  maphide.forceshow:
    default: false
  maphide.admin:
    default: op
    children:
      maphide.player: true
      maphide.admin.toggle: true
      maphide.admin.show: true
      maphide.admin.hide: true
      maphide.admin.status: true
      maphide.admin.config: true
      maphide.admin.set: true
      maphide.admin.reload: true
      maphide.admin.debug: true
      maphide.admin.debug.status: true
      maphide.admin.debug.commands: true
      maphide.admin.debug.permissions: true
      maphide.admin.debug.placeholders: true
  maphide.admin.toggle:
    default: op
  maphide.admin.show:
    default: op
  maphide.admin.hide:
    default: op
  maphide.admin.status:
    default: op
  maphide.admin.config:
    default: op
  maphide.admin.set:
    default: op
  maphide.admin.reload:
    default: op
  maphide.admin.debug:
    default: op
    children:
      maphide.admin.debug.status: true
      maphide.admin.debug.commands: true
      maphide.admin.debug.permissions: true
      maphide.admin.debug.placeholders: true
  maphide.admin.debug.status:
    default: op
  maphide.admin.debug.commands:
    default: op
  maphide.admin.debug.permissions:
    default: op
  maphide.admin.debug.placeholders:
    default: op
